import Link from "next/link";

const SCHEMA = [
  { k: "t_out", d: "outdoor temperature", lo: "-8", hi: "38 °C" },
  { k: "GHI", d: "solar irradiance", lo: "0", hi: "1000 W/m²" },
  { k: "α_sun", d: "solar elevation", lo: "0", hi: "80°" },
  { k: "n_occ", d: "occupancy", lo: "0", hi: "1" },
  { k: "T_set", d: "thermal setpoint", lo: "18", hi: "26 °C" },
  { k: "d", d: "blind deployment", lo: "0", hi: "1" },
  { k: "φ", d: "slat angle", lo: "0", hi: "90°" },
  { k: "v", d: "vent opening", lo: "0", hi: "1" },
];

const OUTPUTS = [
  { k: "E", d: "work-plane illuminance", unit: "lux" },
  { k: "DGP", d: "daylight glare probability", unit: "0–1" },
  { k: "PMV", d: "predicted mean vote", unit: "-3–+3" },
  { k: "E_hvac", d: "HVAC energy demand", unit: "W" },
];

export default function About() {
  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100">
      <header className="border-b border-zinc-200 bg-white/80 backdrop-blur-md dark:border-zinc-800 dark:bg-zinc-950/80">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-3">
          <Link href="/" className="text-sm font-semibold tracking-tight">
            ◫ ClimaFaçade
          </Link>
          <Link
            href="/"
            className="rounded-full border border-zinc-200 px-3 py-1 text-[11px] font-medium text-zinc-600 transition-colors hover:border-zinc-400 dark:border-zinc-700 dark:text-zinc-300"
          >
            ← Back to demo
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl space-y-10 px-5 py-10">
        <section>
          <h1 className="text-4xl font-semibold tracking-tight">
            Machine learning for adaptive building façades
          </h1>
          <p className="mt-3 text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            Dynamic shading façades must reconcile competing objectives — daylight, glare,
            thermal comfort and energy — while responding to what the occupant actually wants.
            Full building-performance simulation is far too slow for real-time operation. This
            demonstrator shows the pipeline proposed for the research: a deep-learning
            surrogate trained on simulation data, deployed inside a model-predictive controller
            that re-optimises the shading configuration every control step.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">1 · Generate simulation data</h2>
          <p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            A fast reference simulator encodes the governing physics of an east-facing office
            room in Wellington: solar position and irradiance, glass and blind transmittance,
            solar gain, natural cross-ventilation via stack effect, and a capacity-limited HVAC
            plant with heating and cooling coils. Random sampling across operating conditions and
            façade configurations produces thousands of labelled scenarios.
          </p>
          <div className="overflow-x-auto rounded-xl border border-zinc-200 dark:border-zinc-800">
            <table className="w-full text-left text-[13px]">
              <thead className="bg-zinc-50 text-zinc-500 dark:bg-zinc-900">
                <tr>
                  <th className="px-4 py-2 font-medium">input</th>
                  <th className="px-4 py-2 font-medium">meaning</th>
                  <th className="px-4 py-2 font-medium">range</th>
                </tr>
              </thead>
              <tbody className="font-mono">
                {SCHEMA.map((r) => (
                  <tr key={r.k} className="border-t border-zinc-100 dark:border-zinc-800">
                    <td className="px-4 py-1.5 font-semibold text-sky-600 dark:text-sky-400">
                      {r.k}
                    </td>
                    <td className="px-4 py-1.5 text-zinc-600">{r.d}</td>
                    <td className="px-4 py-1.5 text-zinc-500">
                      {r.lo} … {r.hi}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-sm text-zinc-500">
            In the full research programme these scenarios would be generated by building
            performance simulation (thermal + daylight + airflow) and multi-objective
            optimisation studies. Here the simulator acts as a stand-in, and the surrogate
            learns its mapping end-to-end.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">2 · Train a surrogate</h2>
          <p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            A two-hidden-layer feedforward network (48+48 units, ReLU) maps the 8 operating
            inputs to the 4 performance targets. Inputs are standardised; the network is trained
            with Adam on 80% of the data and evaluated on the held-out 20%. The loss curves and
            parity plots on the dashboard are produced against that held-out set to quantify
            generalisation rather than memorisation.
          </p>
          <div className="flex flex-wrap gap-2">
            {OUTPUTS.map((o) => (
              <div
                key={o.k}
                className="rounded-xl border border-zinc-200 px-3 py-2 dark:border-zinc-800"
              >
                <span className="font-mono text-sm font-semibold text-emerald-600 dark:text-emerald-400">
                  {o.k}
                </span>
                <div className="mt-0.5 text-xs text-zinc-500">
                  {o.d} · {o.unit}
                </div>
              </div>
            ))}
          </div>
          <p className="text-sm text-zinc-500">
            Once fitted, the weights are serialised to a portable JSON format and executed as a
            small hand-rolled inference routine — no deep-learning runtime required at deployment
            time. Evaluation costs microseconds per façade configuration.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">3 · Closed-loop MPC</h2>
          <p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            Every control step the controller evaluates the surrogate across a gridded set of
            feasible façade configurations and picks the one minimising a weighted objective:
            daylight deficit, glare exceedance, thermal-comfort violation, HVAC energy, plus a
            switching penalty that rejects jitter and promotes robust actuation. Real-time sensor
            readings close the loop: the controller optimises against fresh observations of the
            operating state, and the simulated response is recorded as telemetry.
          </p>
          <div className="rounded-xl border border-zinc-200 p-4 font-mono text-xs dark:border-zinc-800">
            <p className="text-zinc-400">cost(x) =</p>
            <p className="mt-1">
              <span className="text-sky-600 dark:text-sky-400">w_d</span> · daylight(x) +{" "}
              <span className="text-sky-600 dark:text-sky-400">w_g</span> · glare(x) +{" "}
              <span className="text-sky-600 dark:text-sky-400">w_t</span> · thermal(x)
            </p>
            <p className="mt-1">
              + <span className="text-sky-600 dark:text-sky-400">w_e</span> · energy(x) +{" "}
              <span className="text-sky-600 dark:text-sky-400">w_s</span> · switch(x, x₀)
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">4 · Occupant agency and recovery</h2>
          <p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            When the occupant expresses a desire for a different environmental state — more light,
            less glare, warmer conditions — the preference shapes the objective function for the
            next-best action. Once satisfied, the preference weight decays and the controller
            guides the façade back toward the energy-efficient operating baseline, exactly the
            &ldquo;over-ride and recover&rdquo; behaviour targeted in the research.
          </p>
          <div className="flex items-center justify-center gap-2 py-2 text-[13px]">
            <span className="rounded-lg bg-zinc-100 px-3 py-2 dark:bg-zinc-900">occupant asks &ldquo;brighter&rdquo;</span>
            <span className="text-zinc-400">→</span>
            <span className="rounded-lg bg-amber-100 px-3 py-2 text-amber-800 dark:bg-amber-900/50 dark:text-amber-200">
              controller opens shades, slats tilt
            </span>
            <span className="text-zinc-400">→</span>
            <span className="rounded-lg bg-emerald-100 px-3 py-2 text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-200">
              daylight target met → returns to baseline
            </span>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Limitations and next steps</h2>
          <ul className="list-disc space-y-1.5 pl-5 text-base leading-relaxed text-zinc-600 dark:text-zinc-400">
            <li>
              The reference simulator is deliberately lightweight; production work would validate
              against high-fidelity BPS tools (thermal, daylight, CFD airflow).
            </li>
            <li>
              MPC uses a static surrogate; online adaptation and Bayesian calibration to live
              sensor streams is a natural extension.
            </li>
            <li>
              Switching penalties here are heuristic; reinforcement-learning policies or mixed-
              integer optimisation could replace the grid search at larger scale.
            </li>
            <li>
              Uncertainty quantification (e.g. ensembles or MC-dropout) is an explicit next step to
              make the control policy robust to model error.
            </li>
          </ul>
        </section>
      </main>
    </div>
  );
}